name: Validate Swagger
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      workingDirectory:
        description: The root directory for the frontend code base
        required: false
        default: '.'
        type: string
      branch:
        required: false
        default: ${{ github.ref }}
        type: string

jobs:
  gradle-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workingDirectory }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
#       - name: Setup Java
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'corretto'
#           java-version: '17'
#       - name: Setup Gradle
#         uses: gradle/gradle-build-action@v2
#       - name: Run Test
#         run: ./gradlew test
      - name: Validate Swagger cli
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
            command: "validate examples/swagger.yaml"
      - run:  swagger-cli validate --no-schema docs/swagger.yml
#         - name: Send Teams notification for Invalid Swagger Documentation
#           uses: skitionek/notify-microsoft-teams@master
#           if: ${{ failure() }}
#           with:
#             webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
#             raw: >-
#               {
#                 "text": "FAILED: Deployment to ${{ inputs.environment }} for ${{ github.repository }} ${{ inputs.branch }} branch failed due to invalid swagger documentation. Swagger needs to be fixed."
#               }
